version: '3.13'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: 'cassandra:latest'
    networks:
      - app-tier
    expose:
      - '6000'
    ports:
      - '6000:9042'

